# Generated by Django 6.0.5 on 2026-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='ml_prob',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
