# Generated by Django 6.0.5 on 2026-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('signal', 'Signal'), ('analyst', 'Analyst'), ('execution', 'Execution'), ('exit', 'Exit check'), ('session', 'Session')], max_length=12)),
                ('symbol', models.CharField(blank=True, default='', max_length=20)),
                ('decision', models.CharField(max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
