# Generated by Django 6.0.5 on 2026-07-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='stage',
            field=models.CharField(choices=[('signal', 'Signal'), ('ml', 'ML gate'), ('analyst', 'Analyst'), ('execution', 'Execution'), ('exit', 'Exit check'), ('session', 'Session')], max_length=12),
        ),
    ]
