"""Read-only API views for the `portfolio` app."""
import csv
import logging
import zlib
from pathlib import Path

import numpy as np
from django.conf import settings
from django.db.models import QuerySet, Sum
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView

from finpilot.api import ActionView, result_count

from .models import JournalEntry, Order, Position
from .serializers import (
    JournalEntrySerializer, OrderSerializer, PositionSerializer,
)

logger = logging.getLogger(__name__)

# Source of truth for backtest stats — generated by week1/01_data_foundations.py.
# Same file the README results table and one_week_simulation.py both consume.
_BACKTEST_CSV = Path(settings.BASE_DIR).parent / "week1" / "nifty_comparison.csv"


class PortfolioView(APIView):
    """GET /api/portfolio/ — open positions plus an aggregate P&L summary.

    WHY a plain APIView, not a ListAPIView: this endpoint returns a composite
    object (a list of positions PLUS summary numbers), not a bare list. A
    generic list view cannot express that shape.
    """

    def get(self, request):  # pyrefly: ignore[unused-parameter]
        # WHY list(...): the queryset is serialised AND counted; evaluating it
        # once avoids a second COUNT query for the same rows.
        open_positions = list(
            Position.objects.filter(is_open=True).select_related("stock")
        )
        # Realised + unrealised P&L across every position ever held.
        # WHY aggregate(Sum) over a Python sum(): the database computes the
        # total in one query and ships back a single number — summing in
        # Python would pull every Position row into memory first. `or 0`
        # handles the empty-table case, where Sum() returns None.
        total_pnl = Position.objects.aggregate(total=Sum("pnl"))["total"] or 0
        logger.info("PortfolioView: %d open position(s), total P&L %s",
                    len(open_positions), total_pnl)
        return Response({
            "open_positions": PositionSerializer(open_positions, many=True).data,
            "open_count": len(open_positions),
            "total_pnl": total_pnl,
        })


class OrderHistoryView(generics.ListAPIView):
    """GET /api/portfolio/orders/ — full order history, newest first."""

    serializer_class = OrderSerializer

    # See signals/views.py: explicit QuerySet annotation + pyrefly suppression
    # together work around djangorestframework-types declaring
    # `GenericAPIView.get_queryset() -> QuerySet[_MT_co]` without making the
    # parent class `Generic[_MT_co]`.
    def get_queryset(self) -> QuerySet[Order]:  # pyrefly: ignore[bad-override]
        # select_related("stock") joins the Stock in the same query — without
        # it, serialising N orders would fire N extra queries (the N+1 problem).
        return Order.objects.select_related("stock").all()

    def list(self, request, *args, **kwargs):
        # WHY log here, not in get_queryset: a `qs.count()` there would fire an
        # extra COUNT query per request — DRF's paginator already counts the
        # queryset (finpilot.api.result_count reads its number for free).
        response = super().list(request, *args, **kwargs)
        logger.info("OrderHistoryView: returning %s order(s)",
                    result_count(response))
        return response


class PortfolioRiskView(APIView):
    """GET /api/portfolio/risk/ — 1-day VaR / CVaR for the open book.

    Method: HISTORICAL SIMULATION. Apply each of the last ~250 daily return
    vectors to TODAY's position values and read loss quantiles off the
    resulting P&L distribution. WHY not parametric (variance-covariance):
    that assumes normal returns; equity returns have fat tails, and a risk
    number that ignores the tails understates exactly the thing it exists to
    measure. Non-parametric keeps whatever tails the last year actually had —
    the same honesty argument as the orchestrator's bootstrap Monte Carlo.

    Also reports per-position CVaR contributions (each position's average
    loss on the portfolio's tail days) — these sum to the portfolio CVaR by
    construction, so "which holding is my risk?" has an exact answer.

    Prices come from the same cached 1y panel the Quant Lab uses — zero extra
    fetch cost when that cache is warm.
    """

    MIN_DAYS = 60  # below this, quantiles are noise — flag it

    def get(self, request):  # pyrefly: ignore[unused-parameter]
        positions = list(
            Position.objects.filter(is_open=True).select_related("stock"))
        if not positions:
            return Response({
                "open_positions": 0,
                "note": "no open positions — nothing at risk",
            })

        # Late import + module-qualified call so tests can monkeypatch the
        # panel without network.
        from . import quant_views
        try:
            panel = quant_views._tracked_panel()
        except RuntimeError as e:
            return Response({"error": str(e)},
                            status=status.HTTP_503_SERVICE_UNAVAILABLE)

        # Mark each position at its last close; positions whose symbol has no
        # price data fall back to entry price and are disclosed as unpriced.
        syms: list[str] = []
        values: list[float] = []
        unpriced: list[str] = []
        for p in positions:
            sym = p.stock.symbol
            if sym in panel and len(panel[sym]) > 1:
                mark = float(panel[sym]["Close"].iloc[-1])
                syms.append(sym)
            else:
                mark = float(p.avg_entry_price)
                unpriced.append(sym)
                logger.warning("PortfolioRiskView: no prices for %s — marked "
                               "at entry, excluded from simulation", sym)
                continue
            values.append(float(p.quantity) * mark)

        if not syms:
            return Response({"error": "no priced positions to simulate"},
                            status=status.HTTP_503_SERVICE_UNAVAILABLE)

        import pandas as pd
        closes = pd.DataFrame({s: panel[s]["Close"] for s in syms})
        rets = closes.pct_change().dropna()
        v = np.array(values)
        book = float(v.sum())

        # P&L per historical day if that day's returns hit today's book.
        pnl = rets.to_numpy() @ v

        q05 = float(np.percentile(pnl, 5))
        q01 = float(np.percentile(pnl, 1))
        tail = pnl[pnl <= q05]
        var95 = -q05
        cvar95 = float(-tail.mean())
        worst_i = int(np.argmin(pnl))

        # Component CVaR: each position's mean loss on the portfolio's tail
        # days. Linear in positions, so the components sum to the total.
        tail_mask = pnl <= q05
        rmat = rets.to_numpy()[tail_mask]
        comp = -(rmat * v).mean(axis=0)
        # Sort the tuples BEFORE building dicts — sorting dicts on a
        # str|float-valued key trips the checkers (same as MarkowitzWeights).
        ranked = sorted(zip(syms, v, comp), key=lambda t: -float(t[2]))
        contributions = [
            {"symbol": s, "value_rs": round(float(val), 2),
             "cvar_contrib_rs": round(float(c), 2),
             "share_pct": round(float(c) / cvar95 * 100, 1) if cvar95 else 0.0}
            for s, val, c in ranked
        ]

        # Diversification: what standalone VaRs add up to vs the book's VaR.
        standalone = sum(
            -float(np.percentile(rets[s].to_numpy() * val, 5))
            for s, val in zip(syms, v))

        payload = {
            "open_positions": len(positions),
            "book_value_rs": round(book, 2),
            "method": "historical simulation — 1y daily returns applied to "
                      "current position values, marked at last close",
            "days_used": len(rets),
            "thin_history": len(rets) < self.MIN_DAYS,
            "var95_rs": round(var95, 2),
            "var95_pct": round(var95 / book * 100, 2),
            "cvar95_rs": round(cvar95, 2),
            "cvar95_pct": round(cvar95 / book * 100, 2),
            "var99_rs": round(-q01, 2),
            "worst_day_rs": round(float(-pnl[worst_i]), 2),
            "worst_day_date": str(rets.index[worst_i].date()),  # pyright: ignore[reportAttributeAccessIssue]
            "annualised_vol_pct": round(float(pnl.std() / book) * 100
                                        * float(np.sqrt(252)), 2),
            "diversification_benefit_rs": round(standalone - var95, 2),
            "contributions": contributions,
            "unpriced": unpriced,
        }
        logger.info("PortfolioRiskView: book ₹%.0f VaR95 ₹%.0f CVaR95 ₹%.0f "
                    "(%d days)", book, var95, cvar95, len(rets))
        return Response(payload)


class ExecuteOrdersView(ActionView):
    """POST /api/portfolio/execute-orders/ — route today's signals, now.

    Runs the same production task the scheduler would; it cannot bypass the
    ML gate, the analyst, or the risk caps. Contract (202/409/403) lives in
    finpilot.api.ActionView.
    """

    action_name = "execute-orders"

    def get_task(self):
        from .tasks import execute_signal_orders
        return execute_signal_orders


class JournalEntryListView(generics.ListAPIView):
    """GET /api/portfolio/journal/ — the agent's decision diary, newest first.

    Optional filters:
      ?stage=analyst|exit|execution|session|signal   one decision stage
      ?symbol=RELIANCE.NS                            one stock (exact match)

    This is the read side of the agentic layer: every analyst verdict, exit
    decision and supervisor cycle lands in JournalEntry (see portfolio/tasks.py
    and scripts/run_trading_session.py); the dashboard's Journal view renders
    this endpoint so the agent's reasoning is inspectable without the admin.
    """

    serializer_class = JournalEntrySerializer

    def get_queryset(self) -> QuerySet[JournalEntry]:  # pyrefly: ignore[bad-override]
        qs = JournalEntry.objects.all()
        stage = self.request.query_params.get("stage")
        if stage:
            qs = qs.filter(stage=stage)
        symbol = self.request.query_params.get("symbol")
        if symbol:
            qs = qs.filter(symbol=symbol)
        return qs

    def list(self, request, *args, **kwargs):
        response = super().list(request, *args, **kwargs)
        logger.info("JournalEntryListView: returning %s entry(ies)",
                    result_count(response))
        return response


# ── Monte Carlo projection endpoint ──────────────────────────────────────────

ANNUAL_TRADING_DAYS = 252
WEEKS_PER_YEAR = 52

PROJECTION_METHODS = {
    "gaussian": {
        "label": "Gaussian Monte Carlo",
        "description": "Arithmetic returns sampled from a normal distribution.",
    },
    "gbm": {
        "label": "Geometric Brownian motion",
        "description": "Lognormal price paths with continuous compounding.",
    },
    "student_t": {
        "label": "Student-t stress",
        "description": "Fat-tail shocks that generate more extreme paths.",
    },
    "mean_reversion": {
        "label": "Mean-reverting trend",
        "description": "Log prices pulled toward the estimated return trend.",
    },
}


# Canonical cost stack lives in core (framework-free, vectorised) — one
# import, one truth, shared with the orchestrator and the ML dataset builder.
from core.costs import zerodha_round_trip_cost as _zerodha_round_trip_cost  # noqa: E402


# Module-level cache for the backtest CSV: (file mtime, parsed table).
# WHY mtime-keyed: the CSV changes only when week1/01_data_foundations.py is
# re-run. Re-reading + re-parsing it on EVERY projection request is pure waste
# on the hot path; keying the cache on the file's mtime means a refreshed CSV
# is picked up automatically without a server restart.
_stats_cache: tuple[float, dict[str, dict[str, float]]] | None = None


def _load_backtest_stats() -> dict[str, dict[str, float]]:
    """Read the per-stock annual return / Sharpe from nifty_comparison.csv.

    Returned shape: {symbol: {"annual_return_pct": float, "annual_sharpe": float}}.
    Cached at module level, invalidated by the file's mtime — refresh by
    re-running week1/01_data_foundations.py.
    """
    global _stats_cache
    if not _BACKTEST_CSV.exists():
        return {}
    mtime = _BACKTEST_CSV.stat().st_mtime
    if _stats_cache is not None and _stats_cache[0] == mtime:
        return _stats_cache[1]
    with _BACKTEST_CSV.open() as fh:
        table = {
            row["Symbol"]: {
                "annual_return_pct": float(row["Total_Return_%"]),
                "annual_sharpe": float(row["Sharpe"]),
            }
            for row in csv.DictReader(fh)
        }
    _stats_cache = (mtime, table)
    return table


class MonteCarloProjectionView(APIView):
    """GET /api/portfolio/projection/?symbol=...&capital=...&method=...

    Returns a 1-week (configurable) Monte Carlo projection for a single stock:
    percentile price paths for the fan chart, plus summary stats (expected net
    return, P(profit), avg cost) after Zerodha CNC fees.

    The default Gaussian method follows `week1/one_week_simulation.py`; the
    other methods compare different return assumptions while preserving the
    same response shape.

    Query params (all optional):
      symbol        NSE ticker, default RELIANCE.NS
      capital       starting amount in INR, default 1000
      horizon_days  trading days to simulate, default 5 (one week)
      n_sims        path samples; default 2000 — bigger smooths the bands,
                    smaller responds faster. The fan chart only uses
                    percentiles so >5k buys nothing for the UI.
      method        gaussian, gbm, student_t, or mean_reversion

    WHY default n_sims is lower than the CLI's 10k: this endpoint serves
    interactive UI tweaks; sub-100ms beats sharper bands.
    """

    def get(self, request):
        symbol = request.query_params.get("symbol", "RELIANCE.NS")
        capital = float(request.query_params.get("capital", 1000))
        horizon = int(request.query_params.get("horizon_days", 5))
        n_sims = int(request.query_params.get("n_sims", 2000))
        method = request.query_params.get("method", "gaussian").lower()

        # Bracket inputs to sane ranges — defence against accidental
        # `?n_sims=10000000` queries that would tie up a Django thread.
        horizon = max(1, min(horizon, 60))
        n_sims = max(100, min(n_sims, 20_000))
        capital = max(1.0, min(capital, 10_000_000))
        if method not in PROJECTION_METHODS:
            return Response(
                {
                    "error": f"unknown projection method {method!r}",
                    "available_methods": list(PROJECTION_METHODS),
                },
                status=status.HTTP_400_BAD_REQUEST,
            )

        stats_table = _load_backtest_stats()
        if symbol not in stats_table:
            return Response(
                {"error": f"no backtest stats for {symbol!r}",
                 "available": sorted(stats_table.keys())},
                status=status.HTTP_404_NOT_FOUND,
            )

        annual_return = stats_table[symbol]["annual_return_pct"] / 100
        annual_sharpe = stats_table[symbol]["annual_sharpe"]

        # The existing fan chart models portfolio value. The 3D simulation
        # surface needs the same paths expressed as a stock price. Use the
        # latest persisted signal price when available; otherwise return an
        # explicitly labelled index rebased to 100 instead of inventing a quote.
        from signals.models import Signal
        latest_price = (
            Signal.objects
            .filter(stock__symbol=symbol)
            .order_by("-date", "-created_at")
            .values_list("price", flat=True)
            .first()
        )
        starting_price = float(latest_price) if latest_price is not None else 100.0
        price_scale = "market" if latest_price is not None else "indexed"

        # Derive daily mean / std from the 1-yr annual stats. Volatility scales
        # with sqrt(time), so daily_std = annual_vol / sqrt(252) — the famous
        # square-root-of-time identity from quant interview Q14.
        rf = 0.065  # Indian 10-yr G-Sec
        if abs(annual_sharpe) < 0.01:
            annual_vol = 0.25
        else:
            annual_vol = min(max(abs((annual_return - rf) / annual_sharpe), 0.10), 0.45)
        daily_mean = annual_return / ANNUAL_TRADING_DAYS
        daily_std = annual_vol / np.sqrt(ANNUAL_TRADING_DAYS)

        # Generate the same path-matrix shape for every method so the charts
        # can switch models without maintaining separate rendering branches.
        # CRC32 is stable between processes, unlike Python's built-in hash().
        seed = 42 + zlib.crc32(f"{symbol}:{method}".encode("utf-8"))
        rng = np.random.default_rng(seed)
        shocks = rng.normal(size=(n_sims, horizon))

        if method == "gaussian":
            daily_returns = daily_mean + daily_std * shocks
            paths = capital * np.cumprod(
                np.clip(1 + daily_returns, 0.01, None),
                axis=1,
            )
        elif method == "gbm":
            log_returns = daily_mean - 0.5 * daily_std ** 2 + daily_std * shocks
            paths = capital * np.exp(np.cumsum(log_returns, axis=1))
        elif method == "student_t":
            degrees_freedom = 5
            fat_tail_shocks = rng.standard_t(
                degrees_freedom,
                size=(n_sims, horizon),
            )
            fat_tail_shocks /= np.sqrt(
                degrees_freedom / (degrees_freedom - 2)
            )
            daily_returns = daily_mean + daily_std * fat_tail_shocks
            paths = capital * np.cumprod(
                np.clip(1 + daily_returns, 0.01, None),
                axis=1,
            )
        else:
            # Discrete Ornstein-Uhlenbeck dynamics in log-price space. The
            # long-run target advances with the estimated backtest drift.
            reversion_speed = 0.18
            log_levels = np.zeros((n_sims, horizon))
            previous = np.zeros(n_sims)
            for day in range(horizon):
                target = daily_mean * (day + 1)
                previous = (
                    previous
                    + reversion_speed * (target - previous)
                    + daily_std * shocks[:, day]
                )
                log_levels[:, day] = previous
            paths = capital * np.exp(log_levels)
        # Prepend day-0 (the starting capital) so the chart starts at the input.
        paths = np.column_stack([np.full(n_sims, capital), paths])
        price_paths = paths / capital * starting_price

        # Percentile bands — what the fan chart actually draws. We don't ship
        # the raw 2000×6 matrix to the browser; that's overkill for the cone.
        # WHY one np.percentile call: computing all five quantiles in a single
        # pass sorts/partitions the path matrix once instead of five times.
        band_qs = (5, 25, 50, 75, 95)
        bands = np.percentile(paths, band_qs, axis=0)
        pctiles = {
            f"p{q:02d}": [round(float(v), 2) for v in row]
            for q, row in zip(band_qs, bands)
        }
        price_bands = np.percentile(price_paths, band_qs, axis=0)
        price_pctiles = {
            f"p{q:02d}": [round(float(v), 2) for v in row]
            for q, row in zip(band_qs, price_bands)
        }

        # Net-of-cost end-value summary at the final day. The cost stack is
        # vectorised — one array expression covers all n_sims paths (no loop).
        end_values = paths[:, -1]
        costs = _zerodha_round_trip_cost(capital, end_values)
        net_ends = end_values - costs
        net_pct = (net_ends - capital) / capital * 100
        net_p05, net_p50, net_p95 = np.percentile(net_ends, (5, 50, 95))

        logger.info("MonteCarloProjectionView: %s method=%s capital=%.0f horizon=%d "
                    "n_sims=%d -> exp_net=%.2f%% P(profit)=%.1f%%",
                    symbol, method, capital, horizon, n_sims,
                    float(np.mean(net_pct)), float(np.mean(net_pct > 0)) * 100)

        return Response({
            "symbol": symbol,
            "capital": capital,
            "horizon_days": horizon,
            "n_sims": n_sims,
            "method": method,
            "method_label": PROJECTION_METHODS[method]["label"],
            "method_description": PROJECTION_METHODS[method]["description"],
            "available_methods": [
                {"id": key, **metadata}
                for key, metadata in PROJECTION_METHODS.items()
            ],
            # Day index 0..horizon (length horizon+1). The browser uses this as
            # the X axis so it doesn't need to invent its own range.
            "days": list(range(horizon + 1)),
            # Five-band cone — matches the fan chart in one_week_simulation.py.
            "percentiles": pctiles,
            "starting_price": round(starting_price, 2),
            "price_scale": price_scale,
            "price_percentiles": price_pctiles,
            "expected_net_pct": round(float(np.mean(net_pct)), 2),
            "expected_net_end_rs": round(float(np.mean(net_ends)), 2),
            "p05_net_end_rs": round(float(net_p05), 2),
            "p50_net_end_rs": round(float(net_p50), 2),
            "p95_net_end_rs": round(float(net_p95), 2),
            "prob_profit_pct": round(float(np.mean(net_pct > 0)) * 100, 1),
            "avg_cost_rs": round(float(np.mean(costs)), 2),
            "cost_drag_pct": round(float(np.mean(costs) / capital) * 100, 2),
        })
