"""Read-only API views for the `portfolio` app."""
import csv
import logging
from pathlib import Path
from typing import Any

import numpy as np
from django.conf import settings
from django.db.models import QuerySet, Sum
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import Order, Position
from .serializers import OrderSerializer, PositionSerializer

logger = logging.getLogger(__name__)

# Source of truth for backtest stats — generated by week1/01_data_foundations.py.
# Same file the README results table and one_week_simulation.py both consume.
_BACKTEST_CSV = Path(settings.BASE_DIR).parent / "week1" / "nifty_comparison.csv"


class PortfolioView(APIView):
    """GET /api/portfolio/ — open positions plus an aggregate P&L summary.

    WHY a plain APIView, not a ListAPIView: this endpoint returns a composite
    object (a list of positions PLUS summary numbers), not a bare list. A
    generic list view cannot express that shape.
    """

    def get(self, request):  # pyrefly: ignore[unused-parameter]
        # WHY list(...): the queryset is serialised AND counted; evaluating it
        # once avoids a second COUNT query for the same rows.
        open_positions = list(
            Position.objects.filter(is_open=True).select_related("stock")
        )
        # Realised + unrealised P&L across every position ever held.
        # WHY aggregate(Sum) over a Python sum(): the database computes the
        # total in one query and ships back a single number — summing in
        # Python would pull every Position row into memory first. `or 0`
        # handles the empty-table case, where Sum() returns None.
        total_pnl = Position.objects.aggregate(total=Sum("pnl"))["total"] or 0
        logger.info("PortfolioView: %d open position(s), total P&L %s",
                    len(open_positions), total_pnl)
        return Response({
            "open_positions": PositionSerializer(open_positions, many=True).data,
            "open_count": len(open_positions),
            "total_pnl": total_pnl,
        })


class OrderHistoryView(generics.ListAPIView):
    """GET /api/portfolio/orders/ — full order history, newest first."""

    serializer_class = OrderSerializer

    # See signals/views.py: explicit QuerySet annotation + pyrefly suppression
    # together work around djangorestframework-types declaring
    # `GenericAPIView.get_queryset() -> QuerySet[_MT_co]` without making the
    # parent class `Generic[_MT_co]`.
    def get_queryset(self) -> QuerySet[Order]:  # pyrefly: ignore[bad-override]
        # select_related("stock") joins the Stock in the same query — without
        # it, serialising N orders would fire N extra queries (the N+1 problem).
        return Order.objects.select_related("stock").all()

    def list(self, request, *args, **kwargs):
        # WHY log here, not in get_queryset: a `qs.count()` there would fire an
        # extra COUNT query per request — DRF's paginator already counts the
        # queryset, so we read the total from the response it built for free.
        response = super().list(request, *args, **kwargs)
        # `Response.data` is stubbed too tightly to satisfy len() after the
        # isinstance narrowing; it is a dict or list at runtime. Pin to Any —
        # same stub-workaround pattern as week3/llm/__init__.py.
        data: Any = response.data
        total = data.get("count") if isinstance(data, dict) else len(data)
        logger.info("OrderHistoryView: returning %s order(s)", total)
        return response


# ── Monte Carlo projection endpoint ──────────────────────────────────────────

ANNUAL_TRADING_DAYS = 252
WEEKS_PER_YEAR = 52


def _zerodha_round_trip_cost(buy_value, sell_value):
    """Zerodha equity-delivery (CNC) round-trip — matches week1/one_week_simulation.py.

    The same cost stack the README and the orchestrator quote; centralised here
    so the API never disagrees with the standalone scripts.

    Accepts floats OR NumPy arrays — the body is pure arithmetic, so passing
    the whole `end_values` vector computes every simulation's cost in one
    vectorised sweep instead of a Python-level loop over n_sims elements.
    """
    stt = (buy_value + sell_value) * 0.001
    exch = (buy_value + sell_value) * 0.0000325
    sebi = (buy_value + sell_value) * 0.000001
    stamp = buy_value * 0.00015
    gst = (exch + sebi) * 0.18
    dp = 13.5 * 1.18  # ₹13.5 + 18% GST, flat per scrip per sell day
    return stt + exch + sebi + stamp + gst + dp


# Module-level cache for the backtest CSV: (file mtime, parsed table).
# WHY mtime-keyed: the CSV changes only when week1/01_data_foundations.py is
# re-run. Re-reading + re-parsing it on EVERY projection request is pure waste
# on the hot path; keying the cache on the file's mtime means a refreshed CSV
# is picked up automatically without a server restart.
_stats_cache: tuple[float, dict[str, dict[str, float]]] | None = None


def _load_backtest_stats() -> dict[str, dict[str, float]]:
    """Read the per-stock annual return / Sharpe from nifty_comparison.csv.

    Returned shape: {symbol: {"annual_return_pct": float, "annual_sharpe": float}}.
    Cached at module level, invalidated by the file's mtime — refresh by
    re-running week1/01_data_foundations.py.
    """
    global _stats_cache
    if not _BACKTEST_CSV.exists():
        return {}
    mtime = _BACKTEST_CSV.stat().st_mtime
    if _stats_cache is not None and _stats_cache[0] == mtime:
        return _stats_cache[1]
    with _BACKTEST_CSV.open() as fh:
        table = {
            row["Symbol"]: {
                "annual_return_pct": float(row["Total_Return_%"]),
                "annual_sharpe": float(row["Sharpe"]),
            }
            for row in csv.DictReader(fh)
        }
    _stats_cache = (mtime, table)
    return table


class MonteCarloProjectionView(APIView):
    """GET /api/portfolio/projection/?symbol=...&capital=...&horizon_days=...

    Returns a 1-week (configurable) Monte Carlo projection for a single stock:
    percentile price paths for the fan chart, plus summary stats (expected net
    return, P(profit), avg cost) after Zerodha CNC fees.

    Same maths as `week1/one_week_simulation.py` — that's deliberate; the API
    and the standalone script must produce identical numbers so a reviewer who
    runs the CLI sees the same percentiles the dashboard renders.

    Query params (all optional):
      symbol        NSE ticker, default RELIANCE.NS
      capital       starting amount in INR, default 1000
      horizon_days  trading days to simulate, default 5 (one week)
      n_sims        path samples; default 2000 — bigger smooths the bands,
                    smaller responds faster. The fan chart only uses
                    percentiles so >5k buys nothing for the UI.

    WHY default n_sims is lower than the CLI's 10k: this endpoint serves
    interactive UI tweaks; sub-100ms beats sharper bands.
    """

    def get(self, request):
        symbol = request.query_params.get("symbol", "RELIANCE.NS")
        capital = float(request.query_params.get("capital", 1000))
        horizon = int(request.query_params.get("horizon_days", 5))
        n_sims = int(request.query_params.get("n_sims", 2000))

        # Bracket inputs to sane ranges — defence against accidental
        # `?n_sims=10000000` queries that would tie up a Django thread.
        horizon = max(1, min(horizon, 60))
        n_sims = max(100, min(n_sims, 20_000))
        capital = max(1.0, min(capital, 10_000_000))

        stats_table = _load_backtest_stats()
        if symbol not in stats_table:
            return Response(
                {"error": f"no backtest stats for {symbol!r}",
                 "available": sorted(stats_table.keys())},
                status=status.HTTP_404_NOT_FOUND,
            )

        annual_return = stats_table[symbol]["annual_return_pct"] / 100
        annual_sharpe = stats_table[symbol]["annual_sharpe"]

        # Derive daily mean / std from the 1-yr annual stats. Volatility scales
        # with sqrt(time), so daily_std = annual_vol / sqrt(252) — the famous
        # square-root-of-time identity from quant interview Q14.
        rf = 0.065  # Indian 10-yr G-Sec
        if abs(annual_sharpe) < 0.01:
            annual_vol = 0.25
        else:
            annual_vol = min(max(abs((annual_return - rf) / annual_sharpe), 0.10), 0.45)
        daily_mean = annual_return / ANNUAL_TRADING_DAYS
        daily_std = annual_vol / np.sqrt(ANNUAL_TRADING_DAYS)

        # Sample (n_sims × horizon) daily returns -> cumprod -> path matrix.
        # Seeded deterministically per-symbol so reloads don't shimmer.
        rng = np.random.default_rng(42 + (hash(symbol) % 1000))
        daily_returns = rng.normal(daily_mean, daily_std, (n_sims, horizon))
        paths = capital * np.cumprod(1 + daily_returns, axis=1)
        # Prepend day-0 (the starting capital) so the chart starts at the input.
        paths = np.column_stack([np.full(n_sims, capital), paths])

        # Percentile bands — what the fan chart actually draws. We don't ship
        # the raw 2000×6 matrix to the browser; that's overkill for the cone.
        # WHY one np.percentile call: computing all five quantiles in a single
        # pass sorts/partitions the path matrix once instead of five times.
        band_qs = (5, 25, 50, 75, 95)
        bands = np.percentile(paths, band_qs, axis=0)
        pctiles = {
            f"p{q:02d}": [round(float(v), 2) for v in row]
            for q, row in zip(band_qs, bands)
        }

        # Net-of-cost end-value summary at the final day. The cost stack is
        # vectorised — one array expression covers all n_sims paths (no loop).
        end_values = paths[:, -1]
        costs = _zerodha_round_trip_cost(capital, end_values)
        net_ends = end_values - costs
        net_pct = (net_ends - capital) / capital * 100
        net_p05, net_p50, net_p95 = np.percentile(net_ends, (5, 50, 95))

        logger.info("MonteCarloProjectionView: %s capital=%.0f horizon=%d "
                    "n_sims=%d -> exp_net=%.2f%% P(profit)=%.1f%%",
                    symbol, capital, horizon, n_sims,
                    float(np.mean(net_pct)), float(np.mean(net_pct > 0)) * 100)

        return Response({
            "symbol": symbol,
            "capital": capital,
            "horizon_days": horizon,
            "n_sims": n_sims,
            # Day index 0..horizon (length horizon+1). The browser uses this as
            # the X axis so it doesn't need to invent its own range.
            "days": list(range(horizon + 1)),
            # Five-band cone — matches the fan chart in one_week_simulation.py.
            "percentiles": pctiles,
            "expected_net_pct": round(float(np.mean(net_pct)), 2),
            "expected_net_end_rs": round(float(np.mean(net_ends)), 2),
            "p05_net_end_rs": round(float(net_p05), 2),
            "p50_net_end_rs": round(float(net_p50), 2),
            "p95_net_end_rs": round(float(net_p95), 2),
            "prob_profit_pct": round(float(np.mean(net_pct > 0)) * 100, 1),
            "avg_cost_rs": round(float(np.mean(costs)), 2),
            "cost_drag_pct": round(float(np.mean(costs) / capital) * 100, 2),
        })
